### ISSUE TITLE
Sensor Fusion

### ISSUE THREAD

**Issue by PAndreNog** [sparkfun/SparkFun_ICM-20948_ArduinoLibrary#76]
I'm sorry if this is not the best place to make this question, but I wasn't sure where else to do it on.

Im trying to understand and validate the raw data I'm getting from the DMP (acc, gyro and mag) and also understand how one gets from that raw data to the processed data: quaternion.
So questions like:

- What sensor data is calibrated

- How is the sensor fusion done in the DMP to calculate the 9DoF quaternions? 

All of this, of course, considering the ICM 20948. I've searched the dataset but I found nothing to clarify my questions...

**Comment by PaulZC** [comment]
Hi @PAndreNog ,

I'm sorry, I have no answers I can give you. The DMP is a complete "[black box](https://en.wikipedia.org/wiki/Black_box)" and we have no information about how it operates internally or how the sensor data is calibrated. Our knowledge of the DMP is summarized in [DMP.md](https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary/blob/main/DMP.md).

I am going to close this issue, because, sadly, there is really nothing else I can tell you.
Best wishes,
Paul
